name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      
      - name: Build
        run: docker build -t stevekaufman/eshop-frontend .
      
      - name: Push
        run: docker push stevekaufman/eshop-frontend
        
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.DROPLET_SSH_PUBLIC_KEY }}
        run: mkdir ~/.ssh && echo $PRIVATE_KEY > ~/.ssh/id_rsa && echo $PUBLIC_KEY > ~/.ssh/id_rsa.pub

      - name: SSH Login
        env:
          USERNAME: ${{ secrets.DROPLET_USERNAME }}
          HOSTNAME: ${{ secrets.DROPLET_HOSTNAME }}
        run: ssh $HOSTNAME -l $USERNAME

      - name: Docker Pull
        run: docker pull stevekaufman/eshop-frontend

      - name: Docker Stop
        run: docker stop eshop-frontend

      - name: Docker Run
        run: docker run -d --rm --name eshop-frontend -p 8085:8080 stevekaufman/eshop-frontend