name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      
      - name: Build
        run: cd frontend && docker build -t stevekaufman/eshop-frontend .
      
      - name: Push
        run: docker push stevekaufman/eshop-frontend
        
  Deploy:
    needs: Docker

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy
        run: curl https://steve-kaufman.com/deploy/